"""esquema inicial

Revision ID: 0001_initial
Revises: 
Create Date: 2026-06-10 07:48:53.353854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# identificadores de la revisión, usados por Alembic.
revision: str = '0001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('practicas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('postulacion_id', sa.UUID(), nullable=False),
    sa.Column('vacante_id', sa.UUID(), nullable=False),
    sa.Column('estudiante_id', sa.UUID(), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('estado', sa.Enum('en_curso', 'suspendida', 'finalizada', 'reprobada', name='estado_practica_enum'), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin_estimada', sa.Date(), nullable=False),
    sa.Column('fecha_fin_real', sa.Date(), nullable=True),
    sa.Column('calificacion_final', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('programa_academico', sa.String(length=200), nullable=True),
    sa.Column('universidad', sa.String(length=200), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('postulacion_id')
    )
    op.create_index(op.f('ix_practicas_empresa_id'), 'practicas', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_practicas_estado'), 'practicas', ['estado'], unique=False)
    op.create_index(op.f('ix_practicas_estudiante_id'), 'practicas', ['estudiante_id'], unique=False)
    op.create_index(op.f('ix_practicas_vacante_id'), 'practicas', ['vacante_id'], unique=False)
    op.create_table('documentos_practica',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practica_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('contrato_aprendizaje', 'aval_universitario', 'plan_trabajo', 'informe_periodico', 'evaluacion_desempeno', 'certificado_finalizacion', name='tipo_doc_practica_enum'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('nombre_archivo', sa.String(length=200), nullable=True),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('uploaded_by', sa.String(length=50), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluaciones_desempeno',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practica_id', sa.UUID(), nullable=False),
    sa.Column('tipo_evaluador', sa.Enum('empresa', 'universidad', name='tipo_evaluador_enum'), nullable=False),
    sa.Column('calificacion', sa.Numeric(precision=3, scale=1), nullable=False),
    sa.Column('comentarios', sa.Text(), nullable=True),
    sa.Column('puntualidad', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('calidad_trabajo', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('trabajo_en_equipo', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('iniciativa', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('informes_periodicos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('practica_id', sa.UUID(), nullable=False),
    sa.Column('periodo_numero', sa.Integer(), nullable=False),
    sa.Column('descripcion_actividades', sa.Text(), nullable=False),
    sa.Column('logros', sa.Text(), nullable=True),
    sa.Column('dificultades', sa.Text(), nullable=True),
    sa.Column('url_documento', sa.Text(), nullable=True),
    sa.Column('aprobado_por_empresa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['practica_id'], ['practicas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('informes_periodicos')
    op.drop_table('evaluaciones_desempeno')
    op.drop_table('documentos_practica')
    op.drop_index(op.f('ix_practicas_vacante_id'), table_name='practicas')
    op.drop_index(op.f('ix_practicas_estudiante_id'), table_name='practicas')
    op.drop_index(op.f('ix_practicas_estado'), table_name='practicas')
    op.drop_index(op.f('ix_practicas_empresa_id'), table_name='practicas')
    op.drop_table('practicas')
    # ### end Alembic commands ###
